apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: romanowalex/person-service
build:
  artifacts:
  - image: romanowalex/person-service
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: postgres
        chartPath: ./k8s/postgres-chart
      - name: service
        chartPath: ./k8s/service-chart
        setValues:
          domain: "person-service.local"
        artifactOverrides:
          image: romanowalex/person-service
        imageStrategy:
          helm: { }
