apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: romanowalex/person-service
build:
  artifacts:
  - image: romanowalex/person-service
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: postgres
        remoteChart: romanow/postgres
        valuesFiles:
          - k8s/postgres/values.yaml

      - name: person-service
        remoteChart: romanow/java-service
        valuesFiles:
          - k8s/person-service/values.yaml
