spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${DATABASE_PORT:5432}/${DATABASE_NAME:persons}
    username: ${DATABASE_USER:program}
    password: ${DATABAES_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update