spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/persons
    username: program
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update